### ISSUE TITLE
Bug using command quest: TypeError

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#385]
### Current behavior

4|paw  | 2022-04-22T22:37:15: TypeError: Cannot read properties of undefined (reading 'setEmoji')
4|paw  | 2022-04-22T22:37:15:     at startNewRound (/home/pi/discord-bots/paw-and-paper/commands/gameplay/quest.js:292:234)
4|paw  | 2022-04-22T22:37:15:     at runMicrotasks (<anonymous>)
4|paw  | 2022-04-22T22:37:15:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
4|paw  | 2022-04-22T22:37:15:     at async startNewRound (/home/pi/discord-bots/paw-and-paper/commands/gameplay/quest.js:515:12)
4|paw  | 2022-04-22T22:37:15:     at async startNewRound (/home/pi/discord-bots/paw-and-paper/commands/gameplay/quest.js:515:12)
4|paw  | 2022-04-22T22:37:15:     at async startQuest (/home/pi/discord-bots/paw-and-paper/commands/gameplay/quest.js:163:3)
4|paw  | 2022-04-22T22:37:15:     at async Object.module.exports.sendMessage (/home/pi/discord-bots/paw-and-paper/commands/gameplay/quest.js:86:10)
4|paw  | 2022-04-22T22:37:15:     at async execute (/home/pi/discord-bots/paw-and-paper/events/messageCreate.js:129:4)
4|paw  | 2022-04-22T22:37:15:     at async /home/pi/discord-bots/paw-and-paper/commands/gameplay/play.js:268:12

### Expected behavior

/

### Steps to reproduce the behavior

Not enough information

**Comment by MaksiRose** [comment]
The bug could not be replicated. More information is needed.
