### ISSUE TITLE
DiscordAPIError[40060]: Interaction has already been acknowledged at `/scavenge`

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#609]
Created by: maksi#8022 (268402976844939266)

```
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async ButtonInteraction.update (/home/discord-bots/paw-and-paper/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:226:5)
    at async update (/home/discord-bots/paw-and-paper/dist/utils/helperFunctions.js:54:20)
    at async /home/discord-bots/paw-and-paper/dist/commands/gameplay_primary/scavenge.js:294:75
    at async sendFinalMessage (/home/discord-bots/paw-and-paper/dist/commands/gameplay_primary/scavenge.js:294:20)
    at async InteractionCollector.<anonymous> (/home/discord-bots/paw-and-paper/dist/commands/gameplay_primary/scavenge.js:261:21)
{
	"id": "1023048689792602163",
	"application_id": "862718885564252212",
	"type": 2,
	"data": {
		"id": "1021101572039643172",
		"name": "scavenge",
		"type": 1,
		"options": []
	},
	"guild_id": "994666001096519741",
	"channel_id": "1004817300546912418",
	"user_id": "661290745713393664",
	"timestamp": 1663984214972,
	"app_permission": "1072436866625",
	"locale": "en-US",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
Should be fixed through Err 400 catcher
