### ISSUE TITLE
DiscordAPIError[40060]: Interaction has already been acknowledged at `/recover`

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#615]
Created by: maksi#8022 (268402976844939266)

```
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:743:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:549:14)
    at async REST.request (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:988:22)
    at async ButtonInteraction.update (/home/discord-bots/paw-and-paper/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:226:5)
    at async update (/home/discord-bots/paw-and-paper/dist/utils/helperFunctions.js:54:20)
    at async /home/discord-bots/paw-and-paper/dist/commands/gameplay_primary/recover.js:268:122
    at async InteractionCollector.<anonymous> (/home/discord-bots/paw-and-paper/dist/commands/gameplay_primary/recover.js:268:36)
{
	"id": "1025300148684865566",
	"application_id": "862718885564252212",
	"type": 2,
	"data": {
		"id": "1021101572039643171",
		"name": "recover",
		"type": 1,
		"options": []
	},
	"guild_id": "854522091328110595",
	"channel_id": "862716310316122113",
	"user_id": "981906863291502632",
	"timestamp": 1664521004602,
	"app_permission": "4398046511103",
	"locale": "de",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
This specific bug occured when a user was using `/recover`. All emojis were clicked and it showed 12 checkmarks. This would be the point at which the success message should be sent, saying that the user won and that the injury went away. Instead, this error message appeared.

**Comment by MaksiRose** [comment]
Should be fixed through Err 400 catcher
