### ISSUE TITLE
Error: Heal command empty description

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#643]
Created by: maksi#8022 (268402976844939266)

```
Error: Received one or more errors
    at UnionValidator.handle (/home/discord-bots/paw-and-paper/node_modules/@sapphire/shapeshift/dist/index.js:1058:23)
    at UnionValidator.parse (/home/discord-bots/paw-and-paper/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
    at EmbedBuilder.setDescription (/home/discord-bots/paw-and-paper/node_modules/@discordjs/builders/dist/messages/embed/Embed.cjs:57:37)
    at getHealResponse (/home/discord-bots/paw-and-paper/dist/commands/gameplay_maintenance/heal.js:269:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async healInteractionCollector (/home/discord-bots/paw-and-paper/dist/commands/gameplay_maintenance/heal.js:138:13)
    at async Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:503:17)
{
	"id": "1034140666428670042",
	"application_id": "862718885564252212",
	"type": 3,
	"guild_id": "1034129433969303602",
	"channel_id": "1034129433969303605",
	"user_id": "867221856963788802",
	"message": {
		"id": "1034140622778552443",
		"timestamp": 1666628737874,
		"edited_timestamp": 1666628742549,
		"type": 20,
		"application_id": "862718885564252212"
	},
	"timestamp": 1666628748281,
	"app_permission": "1072503975489",
	"locale": "en-US",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
![image](https://user-images.githubusercontent.com/96802571/198064968-856d6614-58bf-42b6-a871-00ab77cf663f.png)
Seems to have something to do with setting an embed description
