### ISSUE TITLE
Error: getMapData returns undefined for friendship command

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#644]
Created by: maksi#8022 (268402976844939266)

```
TypeError: data is undefined
    at getMapData (/home/discord-bots/paw-and-paper/dist/utils/helperFunctions.js:22:15)
    at getFriendshipTexts (/home/discord-bots/paw-and-paper/dist/commands/interaction/friendships.js:88:71)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getFriendshipMessage (/home/discord-bots/paw-and-paper/dist/commands/interaction/friendships.js:110:27)
    at async Object.sendCommand (/home/discord-bots/paw-and-paper/dist/commands/interaction/friendships.js:31:59)
    at async Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:145:13)
{
	"id": "1034268415822667788",
	"application_id": "862718885564252212",
	"type": 2,
	"data": {
		"id": "1021101572089982996",
		"name": "friendships",
		"type": 1,
		"options": []
	},
	"guild_id": "1034129433969303602",
	"channel_id": "1034129433969303605",
	"user_id": "918926248628064256",
	"timestamp": 1666659206110,
	"app_permission": "1072503975489",
	"locale": "en-US",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
This got accidentally fixed in #645
