### ISSUE TITLE
Help command doesn't work when there is no release under the current package version

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#703]
Created by: maksi#8022 (268402976844939266)

```
HttpError: Not Found
    at /home/discord-bots/paw-and-paper/node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.sendCommand (/home/discord-bots/paw-and-paper/dist/commands/miscellaneous/help.js:21:25)
    at async Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:125:17)
{
	"id": "1060207291946782730",
	"application_id": "862718885564252212",
	"type": 2,
	"data": {
		"id": "1021101572089983004",
		"name": "help",
		"command_type": 1,
		"options": []
	},
	"guild_id": "957078956820033606",
	"channel_id": "962969729247637544",
	"user_id": "268402976844939266",
	"timestamp": 1672843516099,
	"app_permission": "1003784367681",
	"locale": "en-US",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
The following needs a catch block:
https://github.com/MaksiRose/paw-and-paper/blob/e3df0b80c35742c7ac3fce21c822d1de08d7c4a4/src/commands/miscellaneous/help.ts#L22-L26
