### ISSUE TITLE
Clicking "approve" on adventuring twice will lead to this error

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#707]
Created by: feliXlib#9798 (705400933072240671)

```
DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/discord-bots/paw-and-paper/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async MessageManager.delete (/home/discord-bots/paw-and-paper/node_modules/discord.js/src/managers/MessageManager.js:254:5)
    at async Message.delete (/home/discord-bots/paw-and-paper/node_modules/discord.js/src/structures/Message.js:784:5)
    at async sendNextRoundMessage (/home/discord-bots/paw-and-paper/dist/commands/interaction/adventure.js:549:9)
    at async Object.sendMessageComponentResponse (/home/discord-bots/paw-and-paper/dist/commands/interaction/adventure.js:200:29)
    at async Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:240:17)
{
	"id": "1060233845762428978",
	"application_id": "862718885564252212",
	"type": 3,
	"data": {
		"component_type": 2,
		"custom_id": "adventure_confirm_@705400933072240671_@268402976844939266"
	},
	"guild_id": "854522091328110595",
	"channel_id": "862716310316122113",
	"user_id": "705400933072240671",
	"message": {
		"id": "1060233799671238686",
		"timestamp": 1672849836033,
		"edited_timestamp": null,
		"type": 20,
		"application_id": "862718885564252212"
	},
	"timestamp": 1672849847022,
	"app_permission": "4398046511103",
	"locale": "en-GB",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
Also, this is how it looked:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/96802571/210605044-79f70c26-c1b6-4693-a530-5b7456085d6b.png">
