### ISSUE TITLE
FollowUp in interactionCreate event fired too soon

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#709]
Created by: howlhound#6792 (743574226824331365)

```
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (/home/discord-bots/paw-and-paper/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:184:64)
    at Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:147:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
	"id": "1060219901106733117",
	"application_id": "862718885564252212",
	"type": 2,
	"data": {
		"id": "1021101572089982996",
		"name": "friendships",
		"command_type": 1,
		"options": []
	},
	"guild_id": "854522091328110595",
	"channel_id": "862716310316122113",
	"user_id": "743574226824331365",
	"timestamp": 1672846522357,
	"app_permission": "4398046511103",
	"locale": "en-US",
	"guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET

ADMIN: Hi, I need some more info on this. As far as I understand it, you tried to execute the /friendships command. Did you actually get a reply to the command alongside this error? If so, what did the reply say?
```

**Comment by MaksiRose** [comment]
https://github.com/MaksiRose/paw-and-paper/blob/e3df0b80c35742c7ac3fce21c822d1de08d7c4a4/src/events/interactionCreate.ts#L143
https://github.com/MaksiRose/paw-and-paper/blob/e3df0b80c35742c7ac3fce21c822d1de08d7c4a4/src/events/interactionCreate.ts#L158

These are the two places. These need to be converted to `respond` functions, but also it needs to be investigated why they fired early in the first place, because the friendship command was executed normally so it should have been awaited.

**Comment by MaksiRose** [comment]
The issue was actually djs sending a wrong error code... But changing those instances to a respond function fixed this issue.
