### ISSUE TITLE
DiscordAPIError[50013]: Missing Permissions (23124egegx795acX)

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#770]
Created by: Δέλτα#3047 (885742117002018826)

Stack:
```
DiscordAPIError[50013]: Missing Permissions
    at async checkLevelRequirements (/home/discord-bots/paw-and-paper/dist/utils/checkRoleRequirements.js:90:25)
    at async Object.sendCommand (/home/discord-bots/paw-and-paper/dist/commands/quid_customization/name.js:109:13)
    at async Object.execute (/home/discord-bots/paw-and-paper/dist/events/interactionCreate.js:125:17)
```
Interaction info:
```json
{
  "id": "1088416007632212008",
  "application_id": "862718885564252212",
  "type": 2,
  "data": {
    "id": "1021101572127727683",
    "name": "name",
    "command_type": 1,
    "options": [
      {
        "name": "name",
        "type": 3,
        "value": "Δέλτα"
      }
    ]
  },
  "guild_id": "1088055111110107169",
  "channel_id": "1088414361174949908",
  "user_id": "885742117002018826",
  "timestamp": 1679568998011,
  "app_permission": "5470550486849",
  "locale": "en-GB",
  "guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
Permission to manage roles is missing
