### ISSUE TITLE
DiscordAPIError[10008]: Unknown Message (23124aoxel871ac6)

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#771]
Created by: Δέλτα#3047 (885742117002018826)

Stack:
```
DiscordAPIError[10008]: Unknown Message
    at async respond (/home/discord-bots/paw-and-paper/dist/utils/helperFunctions.js:42:24)
    at async /home/discord-bots/paw-and-paper/dist/commands/interaction/playfight.js:350:17
    at async startNewRound (/home/discord-bots/paw-and-paper/dist/commands/interaction/playfight.js:280:13)
    at async Object.sendMessageComponentResponse (/home/discord-bots/paw-and-paper/dist/commands/interaction/playfight.js:248:9)
```
Interaction info:
```json
{
  "id": "1088421514245845082",
  "application_id": "862718885564252212",
  "type": 3,
  "data": {
    "component_type": 2,
    "custom_id": "playfight_confirm_tictactoe_@885742117002018826_@813280594796609546"
  },
  "guild_id": "1088055111110107169",
  "channel_id": "1088414361174949908",
  "user_id": "885742117002018826",
  "message": {
    "id": "1088421491340750978",
    "timestamp": 1679570305429,
    "edited_timestamp": null,
    "type": 20,
    "application_id": "862718885564252212"
  },
  "timestamp": 1679570310890,
  "app_permission": "8796093022207",
  "locale": "en-GB",
  "guild_locale": "en-US"
}
```

Additional conversation:
```
FULL CONVERSATION REGARDING THIS TICKET
```

**Comment by MaksiRose** [comment]
They just deleted the playfight message as it looks like. idk.
